export { setup } from "./setup";
export { generateAccount } from "./account";
export { generateCommitment } from "./commitment";
export { getDepositProof, GetDepositProofReturn } from "./get-deposit-proof";
export { getPoseidon } from "./get-poseidon";
export { bigIntToHex } from "./utils/big-int-to-hex";
export { hexToBigInt } from "./utils/hex-to-big-int";
export { generateTransactionProof } from "./generate-transaction-proof";
export { generateNewRootDigestProof } from "./generate-new-root-digest-proof";
export { snarkjs, Proof, Protocols, Curves, Logger, PublicSignals, Groth16, SnarkJS } from "./snarkjs";
