/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DepositVerifierContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DepositVerifierContract__factory>;
    getContractFactory(
      name: "NewRootDigestVerifierContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NewRootDigestVerifierContract__factory>;
    getContractFactory(
      name: "TransactionVerifierContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransactionVerifierContract__factory>;
    getContractFactory(
      name: "ZKlarContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZKlarContract__factory>;

    getContractAt(
      name: "DepositVerifierContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DepositVerifierContract>;
    getContractAt(
      name: "NewRootDigestVerifierContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NewRootDigestVerifierContract>;
    getContractAt(
      name: "TransactionVerifierContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TransactionVerifierContract>;
    getContractAt(
      name: "ZKlarContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZKlarContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
